name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - main  # Trigger this workflow when code is pushed to the 'main' branch

env:
  DOCKER_REGISTRY: docker.io
  DOCKER_REPO: pkarma10/ci_cd  # Your Docker Hub repository
  IMAGE_NAME: python-app
  IMAGE_TAG: latest

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout source code
      - name: Checkout source code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REPO }}:${{ env.IMAGE_TAG }} .

      # Step 4: Push Docker image
      - name: Push Docker image
        run: |
          docker push ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REPO }}:${{ env.IMAGE_TAG }}

      # Step 5: Authenticate to GCP (correct method)
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Step 6: Set up gcloud CLI
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # Step 7: Get GKE credentials
      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER }} --zone ${{ secrets.GKE_ZONE }}

      # Step 8: Deploy to GKE
      - name: Deploy to GKE
        run: |
          kubectl apply -f kubernetes/
